package server

import "infinite-canvas/app-go/internal/handler"

func (a *App) registerRoutes(h *handler.Handler) {
	a.engine.GET("/api/canvases", h.ListCanvases)
	a.engine.POST("/api/canvases", h.CreateCanvas)
	a.engine.GET("/api/canvases/trash", h.ListTrashedCanvases)
	a.engine.GET("/api/canvases/:id/meta", h.GetCanvasMeta)
	a.engine.GET("/api/canvases/:id", h.GetCanvas)
	a.engine.PUT("/api/canvases/:id", h.UpdateCanvas)
	a.engine.DELETE("/api/canvases/:id", h.DeleteCanvas)
	a.engine.POST("/api/canvases/:id/restore", h.RestoreCanvas)
	a.engine.DELETE("/api/canvases/:id/purge", h.PurgeCanvas)

	a.engine.GET("/api/conversations", h.ListConversations)
	a.engine.POST("/api/conversations", h.CreateConversation)
	a.engine.GET("/api/conversations/:id", h.GetConversation)
	a.engine.DELETE("/api/conversations/:id", h.DeleteConversation)

	a.engine.GET("/api/workflows", h.ListWorkflows)
	a.engine.POST("/api/workflows", h.UploadWorkflow)
	a.engine.PUT("/api/workflows/*name", h.SaveWorkflowConfig)
	a.engine.DELETE("/api/workflows/*name", h.DeleteWorkflow)
	a.engine.POST("/api/workflows/*name", h.RunWorkflow)
	a.engine.GET("/api/workflows/*name", h.GetWorkflow)

	a.engine.GET("/api/config", h.GetConfig)
	a.engine.GET("/api/config/token", h.GetGlobalToken)
	a.engine.GET("/api/history", h.GetHistory)
	a.engine.POST("/api/history/delete", h.DeleteHistory)
	a.engine.GET("/api/view", h.ProxyComfyView)
	a.engine.GET("/api/download-output", h.DownloadOutput)
	a.engine.GET("/api/media-preview", h.MediaPreview)
	a.engine.GET("/api/queue_status", h.GetQueueStatus)
	a.engine.POST("/api/canvas-assets/check", h.CheckCanvasAssets)
	a.engine.POST("/api/canvas-assets/download", h.DownloadCanvasAssets)
	a.engine.POST("/api/upload", h.UploadComfyImage)
	a.engine.POST("/api/ai/upload", h.UploadAIReference)
	a.engine.POST("/api/extension/webgen-import", h.ImportWebGeneratorImage)
	a.engine.POST("/api/nodes/media-upload", h.UploadNodeMedia)
	a.engine.POST("/api/nodes/media-delete", h.DeleteNodeMedia)
	a.engine.GET("/api/models", h.ListModels)
	a.engine.GET("/api/providers", h.ListProviders)
	a.engine.PUT("/api/providers", h.SaveProviders)
	a.engine.POST("/api/providers/test-connection", h.TestProviderConnection)
	a.engine.POST("/api/providers/fetch-models", h.FetchModelsFromPayload)
	a.engine.GET("/api/providers/:provider_id/fetch-models", h.FetchModelsFromSavedProvider)
	a.engine.POST("/api/providers/probe-async", h.ProbeAsyncEndpoint)
	a.engine.GET("/api/first-party-keys", h.GetFirstPartyKeys)
	a.engine.PUT("/api/first-party-keys", h.SaveFirstPartyKeys)

	a.engine.POST("/api/online-image", h.OnlineImage)
	a.engine.POST("/api/canvas-image-tasks", h.CreateCanvasImageTask)
	a.engine.GET("/api/canvas-image-tasks/:task_id", h.GetCanvasImageTask)
	a.engine.POST("/api/canvas-video", h.CanvasVideo)
	a.engine.POST("/api/nodes/gpt-image-2", h.NodeGPTImage2)
	a.engine.POST("/api/nodes/seedream", h.NodeSeedream)
	a.engine.POST("/api/nodes/seedance", h.NodeSeedance)
	a.engine.POST("/api/nodes/seedance/status", h.NodeSeedanceStatus)
	a.engine.POST("/api/nodes/seedance/tasks", h.NodeSeedanceTasks)
	a.engine.POST("/api/nodes/seedance/claim", h.NodeSeedanceClaim)
	a.engine.POST("/api/volcengine/assets/groups", h.VolcengineAssetGroups)
	a.engine.POST("/api/volcengine/assets/list", h.VolcengineAssetsList)
	a.engine.POST("/api/volcengine/assets/detail", h.VolcengineAssetDetail)
	a.engine.POST("/api/volcengine/preset-portraits/search", h.VolcenginePresetPortraitsSearch)
	a.engine.POST("/api/volcengine/preset-portraits/filters", h.VolcenginePresetPortraitFilters)
	a.engine.GET("/api/volcengine/assets/preview/:asset_id", h.VolcengineAssetPreview)
	a.engine.POST("/generate", h.GenerateCloud)
	a.engine.POST("/api/ms/generate", h.ModelScopeGenerate)
	a.engine.POST("/api/angle/generate", h.AngleGenerate)
	a.engine.POST("/api/angle/poll_status", h.AnglePollStatus)
	a.engine.POST("/api/canvas-llm", h.CanvasLLM)
	a.engine.POST("/api/chat", h.Chat)
	a.engine.POST("/api/chat/stream", h.ChatStream)

	a.engine.GET("/api/comfyui/instances", h.GetComfyUIInstances)
	a.engine.PUT("/api/comfyui/instances", h.SaveComfyUIInstances)
	a.engine.POST("/api/generate", h.GenerateComfy)
}
